### PR TITLE
de-verbosify a test

### PR DESCRIPTION
**Pull request by greglandrum**
This gets rid of the error-log pollution that was coming from the new tests @bp-kelley added without actually stopping the test from doing logging

### CODE REVIEW

**Comment by bp-kelley** [comment]
@greglandrum did you ensure the test was crashing without the nogil stuff?  That was the blocker I ran into.  It is a fickle test apparently.

**Comment by greglandrum** [comment]
Nope, it works as is and it worked without my change; this doesn’t change any of that

**Comment by bp-kelley** [comment]
I’ll test this on my Mac, it’s reliably crashy with enough cores.

----
Brian Kelley

**Comment by greglandrum** [comment]
> I’ll test this on my Mac, it’s reliably crashy with enough cores.

Sure, but this isn't a blocker for merging #4846 though, right?

**Comment by xavierholt** [comment]
I tested on my Mac - the new tests do indeed fail without the `NOGIL` lines.  Everything is merged to the `python-logging` branch, so it'll land in `master` as a full set (new logging functions + `NOGIL` bugfixes + test output cleanup) once that's merged.

**Comment by bp-kelley** [comment]
Great, I also confirmed.  @greglandrum looks good to go.

**Pull request merged**
